// Auto-generated by loco-sync workflow — do not edit manually
export const SUPPORTED_LOCALES = [
  {
    "code": "fr",
    "label": "Français"
  },
  {
    "code": "en",
    "label": "English"
  },
  {
    "code": "es",
    "label": "Español"
  },
  {
    "code": "it",
    "label": "Italiano"
  },
  {
    "code": "de",
    "label": "Deutsch"
  },
  {
    "code": "nl",
    "label": "Nederlands"
  },
  {
    "code": "pt",
    "label": "Português"
  }
] as const

export type LocaleCode = typeof SUPPORTED_LOCALES[number]['code']
export const SUPPORTED_LANGS = SUPPORTED_LOCALES.map((l) => l.code)
